### PR TITLE
gitignore godot logs folder

### PR DESCRIPTION
**Pull request by pcen**

### CODE REVIEW

**Comment by QuintillusCFC** [comment]
No objections to adding it, but how do you get Godot logs to show up?  Are they at the top level, parallel to "C7" and "C7Engine"?  Trying to figure out why I don't have them, or don't know where to look for them.

**Comment by pcen** [comment]
> No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.

Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise

**Comment by QuintillusCFC** [comment]
> > No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.
> 
> Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise

Could you add the process for building/running from the command line to the Wiki, probably a new section [on this page](https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs)?  I'm not sure that is obvious; at least I've yet to do it.

**Comment by pcen** [comment]
> > > No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.
> > 
> > 
> > Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise
> 
> Could you add the process for building/running from the command line to the Wiki, probably a new section [on this page](https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs)? I'm not sure that is obvious; at least I've yet to do it.



> > > No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.
> > 
> > 
> > Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise
> 
> Could you add the process for building/running from the command line to the Wiki, probably a new section [on this page](https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs)? I'm not sure that is obvious; at least I've yet to do it.

added: https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs#command-line-development

**Comment by pcen** [comment]
> > > No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.
> > 
> > 
> > Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise
> 
> Could you add the process for building/running from the command line to the Wiki, probably a new section [on this page](https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs)? I'm not sure that is obvious; at least I've yet to do it.



> > > No objections to adding it, but how do you get Godot logs to show up? Are they at the top level, parallel to "C7" and "C7Engine"? Trying to figure out why I don't have them, or don't know where to look for them.
> > 
> > 
> > Yes I got `logs/godot.log` at the top level. I got it when I was using the editor last night and a build failed. Unfortunately, I can't remember the error or how I caused it, so I don't know how to reproduce it. Normally I build and run from the command line and I never see logs in the project dir otherwise
> 
> Could you add the process for building/running from the command line to the Wiki, probably a new section [on this page](https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs)? I'm not sure that is obvious; at least I've yet to do it.

added: https://github.com/C7-Game/Prototype/wiki/Developing-and-Setting-Up-IDEs#command-line-development

**Pull request merged**
